-- Up Migration

ALTER TABLE targets
  ALTER COLUMN cancelled_at TYPE TIMESTAMP WITH TIME ZONE
  USING cancelled_at AT TIME ZONE 'UTC';

ALTER TABLE targets
  ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE
  USING created_at AT TIME ZONE 'UTC';

ALTER TABLE targets
  ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE
  USING updated_at AT TIME ZONE 'UTC';

ALTER TABLE steps
  ALTER COLUMN closed_at TYPE TIMESTAMP WITH TIME ZONE
  USING closed_at AT TIME ZONE 'UTC';

ALTER TABLE steps
  ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE
  USING created_at AT TIME ZONE 'UTC';

ALTER TABLE rewards
  ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE
  USING created_at AT TIME ZONE 'UTC';

ALTER TABLE rewards
  ALTER COLUMN accepted_at TYPE TIMESTAMP WITH TIME ZONE
  USING accepted_at AT TIME ZONE 'UTC';

-- Down Migration
